"use client"


const columns = [
  {name: "ID", uid: "CODE_CLT", sortable: true},
  {name: "NAME", uid: "CLIENT", sortable: true},
  {name: "TEL", uid: "TEL", sortable: true},
  {name: "FAX", uid: "FAX", sortable: true},
  {name: "ADRESSE1 LIV", uid: "ADRESSE1LIV"},
  {name: "ADRESSE2 LIV", uid: "ADRESSE2LIV"},
  {name: "ADRESSE1 FACT", uid: "ADRESSE1FACT"},
  {name: "ADRESSE2 FACT", uid: "ADRESSE2FACT"},
  {name: "VILLE LIV", uid: "VILLELIV"},
  {name: "VILLE FACT", uid: "VILLEFACT"},
  {name: "PAYS", uid: "PAYS"},
  {name: "EMAIL", uid: "E_MAIL", sortable: true},
  {name: "BLOQUER", uid: "BLOQUER"},
  {name: "CPLIV", uid: "CPLIV"},
  {name: "CPFACT", uid: "CPFACT"},
  {name: "COMMENTAIRE", uid: "COMMENTAIRE"},
  {name: "ECHEANCE", uid: "ECHEANCE"},
  {name: "APARTIRDE", uid: "APARTIRDE"},
  {name: "OBJECTIF", uid: "OBJECTIF"},
  {name: "Site", uid: "Site"},
  {name: "REF CATEG", uid: "REF_CATEG"},
  {name: "REF_MODEPAIE", uid: "REF_MODEPAIE"},
  {name: "Avantage", uid: "Avantage"},
  {name: "datecreation", uid: "datecreation"},
  {name: "codebadge", uid: "codebadge"},
  {name: "solde du", uid: "solde_du"},
  {name: "plafond", uid: "plafond"},
  {name: "mobile", uid: "mobile"},
  {name: "COMPTE_COMPT", uid: "compte_compt"},
  {name: "categorie", uid: "categorie"},
  {name: "nbpt", uid: "nbpt"},
  {name: "nbptcadeau", uid: "nbptcadeau"},
  {name: "credit", uid: "credit"},
  {name: "soldec", uid: "soldec"},
  {name: "CODE COM", uid: "code_cltcharge"},
  {name: "code cltcharge", uid: "CODE_COM"},
  {name: "personnel", uid: "personnel"},
  {name: "Rremise", uid: "Rremise"},
  {name: "Moisrem", uid: "Moisrem"},
  {name: "REMCAISSE", uid: "REMCAISSE"},
  {name: "soldereel", uid: "soldereel"},
  {name: "plafonnee", uid: "plafonnee"},
  {name: "E01", uid: "E01"},
  {name: "E02", uid: "E02"},
  {name: "E03", uid: "E03"},
  {name: "sync", uid: "sync"},
  {name: "RC", uid: "RC"},
  {name: "ICE", uid: "ICE"},
  {name: "factimediat", uid: "factimediat"},
  {name: "ref modepaiepremier", uid: "ref_modepaiepremier"},
  {name: "telephone2", uid: "telephone2"},
  {name: "code soc", uid: "code_soc"},
  {name: "solde", uid: "solde"},
  {name: "remise", uid: "remise"},
  {name: "tauxsub", uid: "tauxsub"},
  {name: "IF1", uid: "IF1"},
  {name: "ACTIONS", uid: "actions"},
];

const statusOptions = [
  {name: "Active", uid: "active"},
  {name: "Paused", uid: "paused"},
  {name: "Vacation", uid: "vacation"},
];


export {columns, statusOptions};
